# Generated by Django 5.0.1 on 2024-02-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attack_1', models.CharField(max_length=100)),
                ('attack_2', models.CharField(max_length=100)),
                ('attack_3', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('weakness', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
