# Generated by Django 5.0.1 on 2024-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='attack_1_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='attack_2_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='attack_3_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
